version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: albion-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
      - nginx_logs:/var/log/nginx
    depends_on:
      - albion-server
      - albion-client
    networks:
      - albion_net

  # Production Server
  albion-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: albion-server-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8800
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - N8N_WEBHOOK_TOKEN=${N8N_WEBHOOK_TOKEN}
      - ENABLE_TLS=true
    depends_on:
      - mongo
    networks:
      - albion_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Production Client (Next.js)
  albion-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: albion-client-prod
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://albion-market-ai.online/api
    networks:
      - albion_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB
  mongo:
    image: mongo:7
    container_name: albion-mongo-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - albion_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: albion-redis-prod
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - albion_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  albion_net:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  nginx_logs: