services:
  - type: web
    name: albion-client
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: albion-server
    runtime: node
    buildCommand: bun install
    startCommand: bun run src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: N8N_WEBHOOK_TOKEN
        value: ${N8N_WEBHOOK_TOKEN}

databases:
  - name: albion-mongo
    databaseName: albion_prod
    user: albion_user
    plan: starter