import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import QueryProvider from "../hooks/QueryProvider"
import { AuthProvider } from "@/contexts/AuthContext"
import NavBar from "@/components/navBar"   // ✅ client component
import { ErrorBoundary } from "@/components/ErrorBoundary"

export const metadata: Metadata = {
  title: "Albion-Api",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground flex flex-col min-h-screen font-sans antialiased">
        <ErrorBoundary>
          <QueryProvider>
            <AuthProvider>
              <NavBar />
              <main className="flex-1 mt-4 mb-16">{children}</main>
              <footer className="w-full bg-card border-t border-border text-center p-4 text-foreground mt-auto">
                <p>© 2025 Albo. All rights reserved.</p>
                <p className="text-sm text-muted-foreground mt-2">
                  Powered by <a href="https://www.albion-online-data.com/" target="_blank" rel="noopener noreferrer" className="hover:text-primary underline">Albion Online Data API</a> |
                  <a href="https://wiki.albiononline.com/wiki/API:Render_service" target="_blank" rel="noopener noreferrer" className="hover:text-primary underline ml-1">Albion Online Wiki API</a>
                </p>
              </footer>
            </AuthProvider>
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}