import type { Locale } from './seo'

type Guide = { title: string; description: string; intro: string; sections: { title: string; body: string }[]; faq: { q: string; a: string }[]; cta: string; href: string }
export const LAST_CHECKED = '2026-09-23'

export const guides: Record<Locale, Record<string, Guide>> = {
  th: {
    'market-price-freshness': { title: 'วิธีเช็กราคา Albion Online Asia และอ่านความสดของข้อมูล', description: 'วิธีเปรียบเทียบราคาทุกเมืองและอ่าน Fresh, Old, เวลาอัปเดต และ volume อย่างถูกต้อง', intro: 'ราคาบนเว็บมาจากผู้เล่นที่ใช้ AODP Client เปิดตลาดในเกม จึงเป็นราคาล่าสุดที่มีผู้รายงาน ไม่ใช่ราคาสดโดยตรงจากเกม', sections: [{ title: 'อ่าน Fresh และ Old', body: 'Fresh หมายถึงข้อมูลถูกส่งมาไม่เกิน 30 นาที ส่วน Old หมายถึงเก่ากว่านั้นหรือไม่มีเวลาอัปเดต ควรตรวจในเกมอีกครั้งก่อนใช้เงินจำนวนมาก' }, { title: 'ราคาและ volume บอกอะไร', body: 'Best Sell คือราคาตั้งขายต่ำสุด และ Best Buy Order คือคำสั่งซื้อสูงสุดที่รายงานล่าสุด Volume ช่วยบอกสภาพคล่อง แต่ไม่รับประกันว่าจะซื้อหรือขายได้ตามจำนวนนั้น' }], faq: [{ q: 'ทำไมบางเมืองไม่มีราคา?', a: 'ยังไม่มีผู้ใช้ AODP Client เปิดสินค้านั้นในเมืองดังกล่าว หรือข้อมูลเก่าเกินกว่าจะนำมาแสดง' }, { q: 'ราคาเหมือนในเกมเสมอหรือไม่?', a: 'ไม่ ตลาดเปลี่ยนได้ตลอดและข้อมูลขึ้นกับผู้เล่นที่ส่งข้อมูล' }], cta: 'ค้นหาราคาสินค้า', href: '/th' },
    'trade-route-profit-tax': { title: 'วิธีหาเส้นทางซื้อ–ขายและคำนวณกำไรหลังภาษี', description: 'วางแผน trade route Albion Asia พร้อมคำนวณต้นทุน ภาษี และกำไรสุทธิอย่างระมัดระวัง', intro: 'Route Planner เปรียบเทียบราคาที่ผู้เล่นรายงานและหักภาษีตามค่าที่แสดง เพื่อช่วยคัดกรองเส้นทาง—not รับประกันกำไร', sections: [{ title: 'สูตรพื้นฐาน', body: 'กำไรสุทธิ = เงินที่ได้หลังค่าธรรมเนียมและภาษี − ราคาซื้อ − ต้นทุนอื่น เช่น ค่าเดินทาง การตั้งคำสั่งใหม่ และเวลาที่ใช้' }, { title: 'ก่อนออกเดินทาง', body: 'ตรวจ timestamp, volume, จำนวนสินค้า และราคาในเกมทั้งเมืองต้นทางและปลายทาง เส้นทางที่กำไรสูงแต่ข้อมูลเก่ามีความเสี่ยงมากกว่า' }], faq: [{ q: 'ทำไมกำไรจริงต่างจากเว็บ?', a: 'ราคาอาจเปลี่ยน สินค้าอาจขายไม่หมด และภาษีจริงขึ้นกับ Premium, setup และวิธีขายของผู้เล่น' }, { q: 'ควรเริ่มด้วยเงินเท่าไร?', a: 'เริ่มจำนวนน้อยเพื่อทดสอบสภาพคล่องก่อนเพิ่มทุน' }], cta: 'เปิด Route Planner จากรายการสินค้า', href: '/th' },
    'black-market-asia': { title: 'วิธีใช้ Black Market บน Asia พร้อมความเสี่ยงและ volume', description: 'เข้าใจ Black Market ของ Albion Asia วิธีอ่าน buy order, volume และความเสี่ยงก่อนขนสินค้าไป Caerleon', intro: 'Black Market ซื้ออุปกรณ์จากผู้เล่นเพื่อนำไปเป็น loot ราคาและความต้องการเปลี่ยนตามระบบเกม จึงต้องดูทั้งราคาและ volume', sections: [{ title: 'เลือกสินค้าที่ขายได้จริง', body: 'เปรียบเทียบต้นทุนจากเมืองต้นทางกับ buy order ของ Black Market หลังหักค่าใช้จ่าย เลือกสินค้าที่มี volume และข้อมูลใหม่พอ ไม่ดูเปอร์เซ็นต์กำไรเพียงอย่างเดียว' }, { title: 'ความเสี่ยงในการขนส่ง', body: 'เส้นทางเข้า Caerleon อาจผ่านพื้นที่อันตราย มูลค่าที่เสียได้ อุปกรณ์ การหลบหลีก และเวลาที่ใช้ต้องนับเป็นต้นทุนด้วย' }], faq: [{ q: 'Black Market อยู่ที่ไหน?', a: 'อยู่ใน Caerleon และทำงานต่างจากตลาดผู้เล่นทั่วไป' }, { q: 'กำไรสูงแปลว่าดีเสมอไหม?', a: 'ไม่ ข้อมูลเก่า volume ต่ำ หรือความเสี่ยงระหว่างทางอาจทำให้ผลจริงแย่ลง' }], cta: 'เปรียบเทียบราคากับ Black Market', href: '/th' },
    'gold-premium-asia': { title: 'ราคาทองและค่า Premium บน Asia เปลี่ยนเพราะอะไร', description: 'อ่านแนวโน้มราคาทอง Albion Online Asia และเข้าใจปัจจัยที่ทำให้ค่า Premium เปลี่ยนแปลง', intro: 'ราคาทองสะท้อนอุปสงค์และอุปทานของผู้เล่น แนวโน้มย้อนหลังช่วยให้เห็นทิศทาง แต่ไม่สามารถทำนายราคาถัดไปได้แน่นอน', sections: [{ title: 'ปัจจัยที่มีผล', body: 'กิจกรรมในเกม การอัปเดต จำนวนผู้เล่น ความต้องการ Premium และการซื้อขายทองล้วนทำให้ราคาเปลี่ยน' }, { title: 'ใช้กราฟอย่างไร', body: 'ดูทั้งราคาล่าสุด ช่วงสูง–ต่ำ และจำนวนตัวอย่าง อย่าตัดสินใจจากจุดเดียว และตรวจเวลาของข้อมูลเสมอ' }], faq: [{ q: 'กราฟคือราคาสดหรือไม่?', a: 'ไม่ เป็นข้อมูลล่าสุดที่แหล่งข้อมูลชุมชนมีอยู่' }, { q: 'เว็บแนะนำให้ซื้อทองไหม?', a: 'ไม่ กราฟให้ข้อมูลประกอบการตัดสินใจและไม่รับประกันผลตอบแทน' }], cta: 'ดูตลาดทอง Asia', href: '/th/gold' },
  },
  en: {
    'market-price-freshness': { title: 'How to Check Albion Online Asia Prices and Data Freshness', description: 'Compare city prices and correctly read Fresh, Old, timestamps, and market volume.', intro: 'Prices come from players who browse in-game markets while running the AODP Client. They are the latest player reports, not a direct live feed from the game.', sections: [{ title: 'Fresh and Old', body: 'Fresh means the report is no more than 30 minutes old. Old means it is older or has no timestamp. Verify expensive trades in game.' }, { title: 'Price and volume', body: 'Best Sell is the lowest reported listing and Best Buy Order is the highest reported order. Volume suggests liquidity but does not guarantee execution.' }], faq: [{ q: 'Why is a city missing?', a: 'No contributor may have opened that item there recently.' }, { q: 'Do prices always match the game?', a: 'No. Markets move and updates depend on community contributors.' }], cta: 'Search item prices', href: '/en' },
    'trade-route-profit-tax': { title: 'How to Find Trade Routes and Calculate Profit After Tax', description: 'Plan Albion Asia trade routes while accounting for costs, tax, freshness, and liquidity.', intro: 'The Route Planner compares player-reported prices and applies the displayed tax assumptions. It filters opportunities; it does not promise profit.', sections: [{ title: 'Basic formula', body: 'Net profit = proceeds after fees and tax − purchase price − other costs such as travel, relisting, and time.' }, { title: 'Before travelling', body: 'Check timestamps, volume, quantity, and both markets in game. High-margin routes based on old data carry more risk.' }], faq: [{ q: 'Why can actual profit differ?', a: 'Prices move, items may not sell, and actual fees depend on your Premium status and selling method.' }, { q: 'How much should I invest?', a: 'Test liquidity with a small quantity before committing more silver.' }], cta: 'Open an item Route Planner', href: '/en' },
    'black-market-asia': { title: 'Albion Asia Black Market: Risk, Orders, and Volume', description: 'Use Black Market buy orders responsibly by checking freshness, volume, costs, and transport risk.', intro: 'The Black Market buys gear from players to supply loot. Demand and prices are dynamic, so margin must be read together with volume and freshness.', sections: [{ title: 'Choose liquid items', body: 'Compare source cost with the Black Market buy order after expenses. Prefer recent reports and meaningful volume over headline margin alone.' }, { title: 'Transport risk', body: 'Reaching Caerleon can involve dangerous zones. Potential losses, gear, routing, and time are real costs.' }], faq: [{ q: 'Where is the Black Market?', a: 'It is in Caerleon and operates differently from normal player markets.' }, { q: 'Is the highest margin always best?', a: 'No. Old data, low volume, or transport risk can erase the apparent profit.' }], cta: 'Compare Black Market prices', href: '/en' },
    'gold-premium-asia': { title: 'Why Albion Asia Gold and Premium Prices Change', description: 'Understand Albion Asia gold trends and the forces that can move Premium costs.', intro: 'Gold prices reflect player supply and demand. Historical trends provide context, but they cannot reliably predict the next price.', sections: [{ title: 'What moves gold', body: 'Game events, updates, player activity, Premium demand, and gold trading can all affect price.' }, { title: 'Reading the chart', body: 'Review the latest value, range, sample count, and timestamp. Avoid making a decision from one point alone.' }], faq: [{ q: 'Is the chart live?', a: 'No. It shows the latest observations available from the community source.' }, { q: 'Does this site recommend buying gold?', a: 'No. The chart is informational and does not guarantee a return.' }], cta: 'View the Asia gold market', href: '/en/gold' },
  },
}
